"""AI Reports: weekly coaching profiles per team (generated by the worker or on demand)."""
from datetime import datetime, timedelta

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from ..auth import get_current_user, require_analyst
from ..db import get_db
from ..models import Report, User
from ..schemas import ReportOut

router = APIRouter(prefix="/api/reports", tags=["reports"])


@router.get("", response_model=list[ReportOut])
def list_reports(db: Session = Depends(get_db), user: User = Depends(get_current_user),
                 report_type: str | None = None):
    q = db.query(Report).order_by(Report.created_at.desc())
    if report_type:
        q = q.filter(Report.report_type == report_type)
    return [ReportOut.model_validate(r) for r in q.limit(100).all()]


@router.get("/{report_id}", response_model=ReportOut)
def get_report(report_id: int, db: Session = Depends(get_db),
               user: User = Depends(get_current_user)):
    r = db.get(Report, report_id)
    if not r:
        raise HTTPException(404, "Report not found")
    return ReportOut.model_validate(r)


@router.post("/generate", response_model=ReportOut)
def generate_now(db: Session = Depends(get_db), user: User = Depends(require_analyst),
                 team_names: str = "", days: int = 7):
    """Generate a coaching profile report for the last N days on demand."""
    from ..services.reports import generate_coaching_report
    end = datetime.utcnow()
    start = end - timedelta(days=days)
    teams = [t.strip() for t in team_names.split(",") if t.strip()] or None
    r = generate_coaching_report(db, start, end, teams)
    return ReportOut.model_validate(r)
