import React, { useEffect, useState } from "react";
import api from "../api";
import { useToast } from "../components/Toast.jsx";
import { Spinner, EmptyState, Modal } from "../components/ui.jsx";
import Markdown from "../components/Markdown.jsx";
import { shortDate, relativeDate } from "../utils";
import { ReportsIcon } from "../components/Icons.jsx";

export default function Reports() {
  const toast = useToast();
  const [reports, setReports] = useState(null);
  const [viewing, setViewing] = useState(null);
  const [viewLoading, setViewLoading] = useState(false);
  const [genOpen, setGenOpen] = useState(false);
  const [genTeams, setGenTeams] = useState("");
  const [genDays, setGenDays] = useState(7);
  const [generating, setGenerating] = useState(false);

  const load = () => {
    api
      .get("/api/reports")
      .then((d) => setReports(Array.isArray(d) ? d : []))
      .catch((e) => {
        setReports([]);
        toast(e.message, "error");
      });
  };

  useEffect(load, []);

  const openReport = async (r) => {
    if (r.content_md) {
      setViewing(r);
      return;
    }
    setViewLoading(true);
    setViewing(r);
    try {
      const full = await api.get(`/api/reports/${r.id}`);
      setViewing(full);
    } catch (e) {
      toast(e.message, "error");
    } finally {
      setViewLoading(false);
    }
  };

  const generate = async () => {
    setGenerating(true);
    try {
      const q = new URLSearchParams();
      if (genTeams.trim()) q.set("team_names", genTeams.trim());
      q.set("days", genDays);
      await api.post(`/api/reports/generate?${q.toString()}`);
      toast("Report generated", "success");
      setGenOpen(false);
      load();
    } catch (e) {
      toast(e.message, "error");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="page">
      <div className="spread" style={{ marginBottom: 18 }}>
        <div>
          <h1 className="page-title">AI Reports</h1>
          <p className="page-sub">Automated summaries of team performance, generated by AI.</p>
        </div>
        <button className="btn btn-primary" onClick={() => setGenOpen(true)}>
          <ReportsIcon size={15} /> Generate now
        </button>
      </div>

      <div className="card">
        {reports === null ? (
          <Spinner />
        ) : reports.length === 0 ? (
          <EmptyState icon="📄" title="No reports yet" sub='Click "Generate now" to create your first AI report.' />
        ) : (
          <table className="data">
            <thead>
              <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Frequency</th>
                <th>Period</th>
                <th>Teams</th>
                <th>Created</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r) => (
                <tr key={r.id} className="clickable" onClick={() => openReport(r)}>
                  <td style={{ fontWeight: 600 }}>{r.name}</td>
                  <td style={{ textTransform: "capitalize" }}>{r.report_type}</td>
                  <td style={{ textTransform: "capitalize" }}>{r.frequency}</td>
                  <td className="small muted">
                    {shortDate(r.period_start)} – {shortDate(r.period_end)}
                  </td>
                  <td className="small">{(r.team_names || []).join(", ") || "All"}</td>
                  <td className="small muted">{relativeDate(r.created_at)}</td>
                  <td>
                    <button
                      className="btn btn-outline btn-sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        openReport(r);
                      }}
                    >
                      View
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {viewing && (
        <Modal title={viewing.name} onClose={() => setViewing(null)} wide>
          <div className="small muted" style={{ marginBottom: 12 }}>
            {shortDate(viewing.period_start)} – {shortDate(viewing.period_end)} ·{" "}
            {(viewing.team_names || []).join(", ") || "All teams"}
          </div>
          {viewLoading ? <Spinner /> : <Markdown text={viewing.content_md || "_No content._"} />}
        </Modal>
      )}

      {genOpen && (
        <Modal
          title="Generate AI report"
          onClose={() => setGenOpen(false)}
          footer={
            <>
              <button className="btn" onClick={() => setGenOpen(false)}>Cancel</button>
              <button className="btn btn-primary" onClick={generate} disabled={generating}>
                {generating ? "Generating…" : "Generate"}
              </button>
            </>
          }
        >
          <label className="field">
            <span>Team names (comma-separated, blank for all)</span>
            <input
              className="input"
              value={genTeams}
              onChange={(e) => setGenTeams(e.target.value)}
              placeholder="e.g. Acquisition, In Life"
            />
          </label>
          <label className="field">
            <span>Period</span>
            <select className="input" value={genDays} onChange={(e) => setGenDays(Number(e.target.value))}>
              <option value={7}>Last 7 days</option>
              <option value={14}>Last 14 days</option>
              <option value={30}>Last 30 days</option>
            </select>
          </label>
        </Modal>
      )}
    </div>
  );
}
